import nextConfig from "eslint-config-next";
import nextTypeScriptConfig from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "node_modules/**",
      ".git/**",
      "dist/**",
      // Generated by `npx cap sync` and never linted by hand.
      "android/**",
      // Bulk binary asset catalogs, not source.
      "public/fish/**",
      "public/species/**",
      "tsconfig.tsbuildinfo",
    ],
  },
  ...nextConfig,
  ...nextTypeScriptConfig,
];

export default config;
